### ISSUE TITLE
Specify DHT library used

### ISSUE THREAD

**Issue by seamaster101** [AchimPieters/APPLE-HOMEBRIDGE-TEMPERATURE-HUMIDITY-LEVEL#1]
hi,
I tried few of the available DHT libraries, but I'm getting error compiling. 
I suspect I have not installed the exact same library you used:

**********************************
ERROR:
src/main.cpp:11:17: error: 'DHT11' was not declared in this scope
 #define DHTTYPE DHT11
                 ^
src/main.cpp:27:17: note: in expansion of macro 'DHTTYPE'
 DHT dht(DHTPIN, DHTTYPE, 11); // 11 works fine for ESP8266
                 ^
src/main.cpp: In function 'void setup()':
src/main.cpp:44:7: error: 'class DHT' has no member named 'begin'
   dht.begin();           // initialize temperature sensor
       ^
src/main.cpp: In lambda function:
src/main.cpp:69:20: error: 'gettemperature' was not declared in this scope
**********************************
please specify which DHT library you have used.
thank you

**Comment by seamaster101** [comment]
figured it out! needed to move void gettemperature() {} function before void setup {} function. I use ATOM with platformIO it is more strict than Arduino IDE

**Comment by AchimPieters** [comment]
@seamaster101 awesome that you solved it! I use Atom myself too! Have fun with this project!
